['Pelatihan paralegal wilayah sulawesi tenggara',
 'Undangan rapat terkait (KAMTIBNAS)',
 'Permintaan Data',
 'Validasi Data PBB-P2 Tahun 2026 ',
 'Pelaksanaan Musrembang Tingkat Desa/Kelurahan',
 'Undangan Rapat Koordinasi',
 'Pemberitahuan Reaktivasi PBI JK',
 'Pemberitahuan Perlindungan Jaminan Kesehatan',
 'Permintaan Data Pokdarwis',
 'Permohonan Izin Penelitian',
 'Deteksi dini dan CKG di  tempat kerja',
 'Pelatihan paralegal wilayah sulawesi tenggara',
 'Pelatihan paralegal wilayah sulawesi tenggara',
 'Pelatihan paralegal wilayah sulawesi tenggara',
 'isi disposisi yang di isi langsung di sini',
 'ini yang saya input lewat form yang sudah di input dari form',
 'surat nikah pemerintah',
 'Perangkat nikah',
 'Surat keterangan usaha',
 'Undangan Rapat',
 'Keterangan Belum Menikah',
 'Keterangan Kepemilikan Tanah',
 'Surat keterangan kehilangan',
 'Izin Keramaian',
 'Form KK Baru',
 'Akta Kelahiran (Muhammad Althaf)',
 'Daftar Susunan Keluarga',
 'Surat Pengantar Perkawinan',
 'Surat Kematian Suami',
 'Surat Pernyataan tentang Lahan Kosong',
 'Keterangan Domisili',
 'Keterangan Kematian',
 "Undangan Nuzul Qur'an",
 "Undangan Nuzul Qur'an",
 'Permohonan Pengangkutan Kayu',
 'Undangan Rapat',
 'Undangan Rapat',
 'Keterangan belum memiliki rumah',
 'Surat Pernyataan Jual Beli',
 'Pengantar KK',
 'Pengantar Akta',
 'Surat Tugas Pak Desa',
 'Undangan',
 'Undangan Penyuluhan Hukum',
 'Keterangan Mendapatkan KK',
 'Keterangan Identitas',
 'Surat Keterangan Penguburan',
 'Surat Keterangan Tidak Mampu',
 'Keterangan Dispensasi',
 'Izin Pesta',
 'Surat Keterangan Pindah Wilayah',
 'Surat Keterangan Kelakuan Baik',
 'Undangan Rembuk Stunting',
 'Undangan',
 'Surat Keterangan Pindah',
 'Surat Ahli Waris',
 'Keterangan Wali Murid',
 'ini surat keluar tambah nikah']

array(['2026', 'ahli', 'akta', 'althaf', 'an', 'baik', 'baru', 'beli',
       'belum', 'ckg', 'daftar', 'dan', 'dari', 'data', 'desa', 'deteksi',
       'di', 'dini', 'dispensasi', 'disposisi', 'domisili', 'form',
       'hukum', 'identitas', 'ini', 'input', 'isi', 'izin', 'jaminan',
       'jk', 'jual', 'kamtibnas', 'kayu', 'kehilangan', 'kelahiran',
       'kelakuan', 'keluar', 'keluarga', 'kelurahan', 'kematian',
       'kepemilikan', 'keramaian', 'kerja', 'kesehatan', 'keterangan',
       'kk', 'koordinasi', 'kosong', 'lahan', 'langsung', 'lewat',
       'mampu', 'memiliki', 'mendapatkan', 'menikah', 'muhammad', 'murid',
       'musrembang', 'nikah', 'nuzul', 'p2', 'pak', 'paralegal', 'pbb',
       'pbi', 'pelaksanaan', 'pelatihan', 'pemberitahuan', 'pemerintah',
       'penelitian', 'pengangkutan', 'pengantar', 'penguburan',
       'penyuluhan', 'perangkat', 'perkawinan', 'perlindungan',
       'permintaan', 'permohonan', 'pernyataan', 'pesta', 'pindah',
       'pokdarwis', 'qur', 'rapat', 'reaktivasi', 'rembuk', 'rumah',
       'saya', 'sini', 'stunting', 'suami', 'sudah', 'sulawesi', 'surat',
       'susunan', 'tahun', 'tambah', 'tanah', 'tempat', 'tenggara',
       'tentang', 'terkait', 'tidak', 'tingkat', 'tugas', 'undangan',
       'usaha', 'validasi', 'wali', 'waris', 'wilayah', 'yang'],
      dtype=object)